backend:
  name: test-repo
  branch: master

media_folder: public/posts
public_folder: /public/img
publish_mode: editorial_workflow

collections:
  - name: auteurs
    label: Auteurs
    folder: "auteurs"
    create: true
    fields:
      - {name: naam, label: Naam}

  - name: tags
    label: Tags
    folder: "tags"
    create: true
    fields:
      - {name: naam, label: Naam}


  - name: posts
    label: Posts
    folder: "posts"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "post.template"}
      - {label: "Titel", name: "titel", widget: "string"}
      - {label: "Subtitel", name: "Subtitel", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - name: auteur
        label: Auteur
        widget: relation
        collection: auteurs
        searchFields: [naam]
        valueField: naam
      - name: tags
        label: Tags
        widget: relation
        collection: tags
        searchFields: [naam]
        multiple: true
        valueField: naam
        required: false



