backend:
  name: test-repo
  branch: master

media_folder: public/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    description: >
      Artikelen
    folder: "src/pages/blog"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "post.template"}
      - {label: "Titel", name: "titel", widget: "string"}
      - {label: "Subtitel", name: "Subtitel", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: 'Onderwerp'
        name: "onderwerp"
        widget: select
        options: ["history", "nature", "human","quirky","space","tech"]
      - label: "Post auteur"
        name: "auteur"
        widget: "relation"
        collection: "auteurs"
        display_fields: ['naam']
        search_fields: ['naam']
        value_field: 'naam'
      - label: "Post tags"
        name: "tags"
        widget: "relation"
        collection: "tags"
        display_fields: ['naam']
        search_fields: ['naam']
        value_field: 'naam'

  - name: "auteurs"
    label: "Auteurs"
    label_singular: "auteur"
    description: >
      auteurs die stukken hebben geschreven
    folder: "src/pages/blog"
    create: true
    fields:
      - {label: "Naam", name: "naam", widget: "string"}
  - name: "tags"
    label: "Tags"
    label_singular: "tag"
    description: >
      tags van de verschillende stukken
    folder: "src/pages/blog"
    create: true
    fields:
      - {label: "Naam", name: "naam", widget: "string"}



